version: "3.9"
services:
  web:
    build: .
    env_file:
        - ./.env.prod
    depends_on:
        - db
    expose:
        - 5000
    ports:
        - 5000:5000
    volumes:
        - .:/web
  redis:
    image: redis
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashlearn
    image: postgres:latest
    networks:
        - default
    ports:
        - 5405:5432
    env_file:
        - ./.env.prod
    volumes:
        - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
      external: true
