version: "3.9"
services:
  web:
    build: .
    env_file:
     - .env.dev
    depends_on:
     - db
    ports:
     - 5000:5000
    volumes:
     - .:/web
  redis:
    image: redis
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashlearn
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
