"""empty message

Revision ID: 56af39016a6f
Revises: 342933836733
Create Date: 2020-11-23 18:34:39.248994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56af39016a6f'
down_revision = '342933836733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
