"""add onboarding boolean on user model

Revision ID: ad91dff54d96
Revises: 56af39016a6f
Create Date: 2020-11-23 18:49:01.721820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad91dff54d96'
down_revision = '56af39016a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded')
    # ### end Alembic commands ###
