"""empty message

Revision ID: dc28c32e37fe
Revises: e0672fe2debf
Create Date: 2021-02-16 11:47:46.447005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc28c32e37fe"
down_revision = "ad91dff54d96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint("users_username", ["username"])
        batch_op.create_unique_constraint("users_email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("users_username", type_="unique")
        batch_op.drop_constraint("users_email", type_="unique")

    # ### end Alembic commands ###
